-- scratch/database-update.sql
-- Run this script in your Supabase Dashboard SQL Editor to add the missing tables,
-- columns, triggers, and views required for onboarding and ID card verification.

-- ─── 1. CREATE UNIVERSITIES TABLE & RLS ───
CREATE TABLE IF NOT EXISTS public.universities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  domain TEXT NOT NULL UNIQUE,
  short_name TEXT NOT NULL UNIQUE,
  primary_color TEXT NOT NULL,
  secondary_color TEXT NOT NULL,
  logo_url TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

ALTER TABLE public.universities ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow public read access on universities" ON public.universities;
CREATE POLICY "Allow public read access on universities" 
  ON public.universities FOR SELECT 
  TO authenticated 
  USING (true);

-- Seed all 313 universities
INSERT INTO public.universities (name, domain, short_name, primary_color, secondary_color)
VALUES
  ('University of Lagos', 'unilag.edu.ng', 'UNILAG', '#002244', '#FFD700'),
  ('University of Ibadan', 'ui.edu.ng', 'UI', '#004B49', '#FFD700'),
  ('FAF Campus Demo', 'fafcampus.site', 'FAF Demo', '#8b5cf6', '#6366f1'),
  ('Redeemer''s University', 'run.edu.ng', 'RUN', '#0a2f5c', '#e5b73b'),
  ('Abubakar Tafawa Balewa University, Bauchi', 'atbu.edu.ng', 'ATBU', '#002244', '#FFD700'),
  ('Ahmadu Bello University, Zaria', 'abu.edu.ng', 'ABU', '#004B49', '#FFD700'),
  ('Bayero University, Kano', 'buk.edu.ng', 'BUK', '#7A1C1C', '#C0C0C0'),
  ('Federal University Gashua, Yobe', 'fug.edu.ng', 'FUG', '#1E3A8A', '#3B82F6'),
  ('Federal University of Petroleum Resources, Effurun', 'fupr.edu.ng', 'FUPR', '#4C1D95', '#F59E0B'),
  ('Federal University of Technology, Akure', 'futa.edu.ng', 'FUTA', '#065F46', '#10B981'),
  ('Federal University of Technology, Minna', 'futminna.edu.ng', 'FUTMINNA', '#1E293B', '#94A3B8'),
  ('Federal University of Technology, Owerri', 'futo.edu.ng', 'FUTO', '#581C87', '#C084FC'),
  ('Federal University, Dutse, Jigawa State', 'fu.edu.ng', 'FU', '#881337', '#FB7185'),
  ('Federal University, Dutsin-Ma, Katsina', 'fu2.edu.ng', 'FU2', '#701A75', '#F472B6'),
  ('Federal University, Kashere, Gombe State', 'fu3.edu.ng', 'FU3', '#1E1B4B', '#818CF8'),
  ('Federal University, Lafia, Nasarawa State', 'fu4.edu.ng', 'FU4', '#311042', '#E0B0FF'),
  ('Federal University, Lokoja, Kogi State', 'fu5.edu.ng', 'FU5', '#002244', '#FFD700'),
  ('Alex Ekwueme University, Ndufu-Alike, Ebonyi State', 'aeu.edu.ng', 'AEU', '#004B49', '#FFD700'),
  ('Federal University, Otuoke, Bayelsa', 'fu6.edu.ng', 'FU6', '#7A1C1C', '#C0C0C0'),
  ('Federal University, Oye-Ekiti, Ekiti State', 'fu7.edu.ng', 'FU7', '#1E3A8A', '#3B82F6'),
  ('Federal University, Wukari, Taraba State', 'fu8.edu.ng', 'FU8', '#4C1D95', '#F59E0B'),
  ('Federal University, Birnin Kebbi', 'fu9.edu.ng', 'FU9', '#065F46', '#10B981'),
  ('Federal University, Gusau Zamfara', 'fu10.edu.ng', 'FU10', '#1E293B', '#94A3B8'),
  ('Michael Okpara University of Agriculture, Umudike', 'moua.edu.ng', 'MOUA', '#581C87', '#C084FC'),
  ('Modibbo Adama University of Technology, Yola', 'maut.edu.ng', 'MAUT', '#881337', '#FB7185'),
  ('National Open University of Nigeria, Abuja', 'noun.edu.ng', 'NOUN', '#701A75', '#F472B6'),
  ('Nigeria Police Academy, Wudil', 'npa.edu.ng', 'NPA', '#1E1B4B', '#818CF8'),
  ('Nigerian Defence Academy, Kaduna', 'nda.edu.ng', 'NDA', '#311042', '#E0B0FF'),
  ('Nnamdi Azikiwe University, Awka', 'unizik.edu.ng', 'UNIZIK', '#002244', '#FFD700'),
  ('Obafemi Awolowo University, Ile-Ife', 'oau.edu.ng', 'OAU', '#004B49', '#FFD700'),
  ('University of Abuja, Gwagwalada', 'uniabuja.edu.ng', 'UNIABUJA', '#7A1C1C', '#C0C0C0'),
  ('Federal University of Agriculture, Abeokuta', 'funaab.edu.ng', 'FUNAAB', '#1E3A8A', '#3B82F6'),
  ('Joseph Sarwuan Tarka University, Makurdi', 'jstu.edu.ng', 'JSTU', '#4C1D95', '#F59E0B'),
  ('University of Benin', 'uniben.edu.ng', 'UNIBEN', '#065F46', '#10B981'),
  ('University of Calabar', 'uc.edu.ng', 'UC', '#1E293B', '#94A3B8'),
  ('University of Ilorin', 'unilorin.edu.ng', 'UNILORIN', '#581C87', '#C084FC'),
  ('University of Jos', 'unijos.edu.ng', 'UNIJOS', '#881337', '#FB7185'),
  ('University of Maiduguri', 'unimaid.edu.ng', 'UNIMAID', '#701A75', '#F472B6'),
  ('University of Nigeria, Nsukka', 'unn.edu.ng', 'UNN', '#1E1B4B', '#818CF8'),
  ('University of Port-Harcourt', 'uniport.edu.ng', 'UNIPORT', '#311042', '#E0B0FF'),
  ('University of Uyo', 'uniuyo.edu.ng', 'UNIUYO', '#002244', '#FFD700'),
  ('Usumanu Danfodiyo University, Sokoto', 'udus.edu.ng', 'UDUS', '#004B49', '#FFD700'),
  ('Nigerian Maritime University, Okerenkoko, Delta State', 'nmu.edu.ng', 'NMU', '#7A1C1C', '#C0C0C0'),
  ('Air Force Institute of Technology, Kaduna', 'afit.edu.ng', 'AFIT', '#1E3A8A', '#3B82F6'),
  ('Nigerian Army University, Biu', 'nau.edu.ng', 'NAU', '#4C1D95', '#F59E0B'),
  ('Federal University of Health Sciences, Otukpo, Benue State', 'fuhs.edu.ng', 'FUHS', '#065F46', '#10B981'),
  ('Federal University of Agriculture, Zuru, Kebbi State', 'fua.edu.ng', 'FUA', '#1E293B', '#94A3B8'),
  ('Federal University of Technology, Babura, Jigawa State', 'fut-babura.edu.ng', 'FUT-Babura', '#581C87', '#C084FC'),
  ('Federal University of Technology, Ikot Abasi, Akwa Ibom State', 'fut-ikotabasi.edu.ng', 'FUT-IkotAbasi', '#881337', '#FB7185'),
  ('Federal University of Health Sciences, Azare, Bauchi State', 'fuhs2.edu.ng', 'FUHS2', '#701A75', '#F472B6'),
  ('Federal University of Health Sciences, Ila Orangun, Osun State', 'fuhs3.edu.ng', 'FUHS3', '#1E1B4B', '#818CF8'),
  ('David Nweze Umahi Federal University of Medical Sciences, Uburu', 'dnufums.edu.ng', 'DNUFUMS', '#311042', '#E0B0FF'),
  ('Admiralty University, Ibusa, Delta State', 'au.edu.ng', 'AU', '#002244', '#FFD700'),
  ('Federal University of Transportation, Daura, Katsina', 'fut.edu.ng', 'FUT', '#004B49', '#FFD700'),
  ('African Aviation and Aerospace University', 'aaau.edu.ng', 'AAAU', '#7A1C1C', '#C0C0C0'),
  ('National University of Science and Technology, Abuja', 'nust.edu.ng', 'NUST', '#1E3A8A', '#3B82F6'),
  ('Federal University of Agriculture, Bassam-Biri, Bayelsa', 'fua2.edu.ng', 'FUA2', '#4C1D95', '#F59E0B'),
  ('Federal University of Health Sciences, Kwale, Delta State', 'fuhs4.edu.ng', 'FUHS4', '#065F46', '#10B981'),
  ('Federal University of Health Sciences, Katsina', 'fuhs5.edu.ng', 'FUHS5', '#1E293B', '#94A3B8'),
  ('Federal University of Agriculture, Mubi', 'fua3.edu.ng', 'FUA3', '#581C87', '#C084FC'),
  ('Federal University of Education, Zaria, Kaduna State', 'fue.edu.ng', 'FUE', '#881337', '#FB7185'),
  ('Alvan Ikoku Federal University of Education, Owerri, Imo State', 'aifue.edu.ng', 'AIFUE', '#701A75', '#F472B6'),
  ('Yusuf Maitama Sule Federal University of Education, Kano', 'ymsfue.edu.ng', 'YMSFUE', '#1E1B4B', '#818CF8'),
  ('Adeyemi Federal University of Education, Ondo', 'afue.edu.ng', 'AFUE', '#311042', '#E0B0FF'),
  ('Federal University of Allied Health Sciences, Enugu', 'fuahs.edu.ng', 'FUAHS', '#002244', '#FFD700'),
  ('Federal University of Medicine and Medical Sciences, Abeokuta', 'fumms.edu.ng', 'FUMMS', '#004B49', '#FFD700'),
  ('Federal University of Education, Pankshin, Plateau State', 'fue2.edu.ng', 'FUE2', '#7A1C1C', '#C0C0C0'),
  ('Federal University of Education, Kontagora, Niger State', 'fue3.edu.ng', 'FUE3', '#1E3A8A', '#3B82F6'),
  ('University of Maritime Studies, Oron, Akwa Ibom State', 'ums.edu.ng', 'UMS', '#4C1D95', '#F59E0B'),
  ('Federal University of Environment and Technology, Tai Town, Ogoniland, Rivers State', 'fuet.edu.ng', 'FUET', '#065F46', '#10B981'),
  ('Federal University of Applied Sciences, Kachia, Kaduna State', 'fuas.edu.ng', 'FUAS', '#1E293B', '#94A3B8'),
  ('Tai Solarin Federal University of Education, Ijagun, Ijebu Ode', 'tasued.edu.ng', 'TASUED', '#581C87', '#C084FC'),
  ('Federal University of Agriculture and Developmental Studies, Iragbiji, Osun State', 'fuads.edu.ng', 'FUADS', '#881337', '#FB7185'),
  ('Federal University of Technology and Environmental Studies, Iyin-Ekiti, Ekiti State', 'futes.edu.ng', 'FUTES', '#701A75', '#F472B6'),
  ('Federal University of Agriculture and Technology, Okeho, Oyo State', 'fuat.edu.ng', 'FUAT', '#1E1B4B', '#818CF8'),
  ('Federal University of Health Science and Technology, Tsafe', 'fuhst.edu.ng', 'FUHST', '#311042', '#E0B0FF'),
  ('Federal University of Agriculture and Technology, Obio-Akpa, Akwa Ibom State', 'fuat2.edu.ng', 'FUAT2', '#002244', '#FFD700'),
  ('Federal University of Science and Technology, Epe', 'fust.edu.ng', 'FUST', '#004B49', '#FFD700'),
  ('Federal University of Science and Technology, Kabo, Kano', 'fust2.edu.ng', 'FUST2', '#7A1C1C', '#C0C0C0'),
  ('Rivers State University', 'rsu.edu.ng', 'RSU', '#1E3A8A', '#3B82F6'),
  ('Ambrose Alli University, Ekpoma', 'aau.edu.ng', 'AAU', '#4C1D95', '#F59E0B'),
  ('Abia State University, Uturu', 'absu.edu.ng', 'ABSU', '#065F46', '#10B981'),
  ('Ekiti State University', 'eksu.edu.ng', 'EKSU', '#1E293B', '#94A3B8'),
  ('Enugu State University of Science and Technology', 'esut.edu.ng', 'ESUT', '#581C87', '#C084FC'),
  ('Olabisi Onabanjo University, Ago Iwoye', 'oou.edu.ng', 'OOU', '#881337', '#FB7185'),
  ('Lagos State University, Ojo', 'lasu.edu.ng', 'LASU', '#701A75', '#F472B6'),
  ('Ladoke Akintola University of Technology, Ogbomoso', 'lautech.edu.ng', 'LAUTECH', '#1E1B4B', '#818CF8'),
  ('Rev. Fr. Moses Orshio Adasu Univ. (formerly Benue State Univ.), Makurdi', 'rfmoaubsu.edu.ng', 'RFMOAUBSU', '#311042', '#E0B0FF'),
  ('Delta State University, Abraka', 'delsu.edu.ng', 'DELSU', '#002244', '#FFD700'),
  ('Imo State University, Owerri', 'imsu.edu.ng', 'IMSU', '#004B49', '#FFD700'),
  ('Adekunle Ajasin University, Akungba', 'aaua.edu.ng', 'AAUA', '#7A1C1C', '#C0C0C0'),
  ('Prince Abubakar Audu University, Anyigba', 'paau.edu.ng', 'PAAU', '#1E3A8A', '#3B82F6'),
  ('Chukwuemeka Odumegwu Ojukwu University, Uli', 'coou.edu.ng', 'COOU', '#4C1D95', '#F59E0B'),
  ('Ebonyi State University, Abakaliki', 'ebsu.edu.ng', 'EBSU', '#065F46', '#10B981'),
  ('Aliko Dangote University of Science & Technology, Wudil', 'adustech.edu.ng', 'ADUSTECH', '#1E293B', '#94A3B8'),
  ('Niger Delta University, Yenagoa', 'ndu.edu.ng', 'NDU', '#581C87', '#C084FC'),
  ('Adamawa State University, Mubi', 'adsu.edu.ng', 'ADSU', '#881337', '#FB7185'),
  ('Nasarawa State University, Keffi', 'nsuk.edu.ng', 'NSUK', '#701A75', '#F472B6'),
  ('University of Cross River State, Calabar', 'ucrs.edu.ng', 'UCRS', '#1E1B4B', '#818CF8'),
  ('Gombe State University', 'gsu.edu.ng', 'GSU', '#311042', '#E0B0FF'),
  ('Kaduna State University', 'kasu.edu.ng', 'KASU', '#002244', '#FFD700'),
  ('Ibrahim Badamasi Babangida University, Lapai', 'ibbu.edu.ng', 'IBBU', '#004B49', '#FFD700'),
  ('Plateau State University, Bokkos', 'plasu.edu.ng', 'PLASU', '#7A1C1C', '#C0C0C0'),
  ('Yobe State University, Damaturu', 'ysu.edu.ng', 'YSU', '#1E3A8A', '#3B82F6'),
  ('Kebbi State University of Science and Technology, Aliero', 'ksust.edu.ng', 'KSUST', '#4C1D95', '#F59E0B'),
  ('Umar Musa Yar''Adua University, Katsina', 'umyau.edu.ng', 'UMYAU', '#065F46', '#10B981'),
  ('Osun State University, Osogbo', 'osu.edu.ng', 'OSU', '#1E293B', '#94A3B8'),
  ('Olusegun Agagu University of Science & Technology, Okitipupa', 'oaust.edu.ng', 'OAUST', '#581C87', '#C084FC'),
  ('Taraba State University, Jalingo', 'tasu.edu.ng', 'TASU', '#881337', '#FB7185'),
  ('Kwara State University, Ilorin', 'kwasu.edu.ng', 'KWASU', '#701A75', '#F472B6'),
  ('Sokoto State University', 'ssu.edu.ng', 'SSU', '#1E1B4B', '#818CF8'),
  ('Akwa Ibom State University, Ikot Akpaden', 'aisu.edu.ng', 'AISU', '#311042', '#E0B0FF'),
  ('Ignatius Ajuru University of Education, Rumuolumeni', 'iaue.edu.ng', 'IAUE', '#002244', '#FFD700'),
  ('Bauchi State University, Gadau', 'basug.edu.ng', 'BASUG', '#004B49', '#FFD700'),
  ('Northwest University, Kano', 'nu.edu.ng', 'NU', '#7A1C1C', '#C0C0C0'),
  ('First Technical University, Ibadan', 'tech-u.edu.ng', 'Tech-U', '#1E3A8A', '#3B82F6'),
  ('Sule Lamido University, Kafin Hausa, Jigawa', 'slu.edu.ng', 'SLU', '#4C1D95', '#F59E0B'),
  ('University of Medical Sciences, Ondo City', 'unimed.edu.ng', 'UNIMED', '#065F46', '#10B981'),
  ('Edo State University, Iyamho', 'edsu.edu.ng', 'EDSU', '#1E293B', '#94A3B8'),
  ('Kingsley Ozumba Mbadiwe University, Ogboko, Imo State', 'komu.edu.ng', 'KOMU', '#581C87', '#C084FC'),
  ('University of Africa, Toru Orua, Bayelsa State', 'uat.edu.ng', 'UAT', '#881337', '#FB7185'),
  ('Kashim Ibrahim University (formerly Borno State Univ.), Maiduguri', 'kiubsu.edu.ng', 'KIUBSU', '#701A75', '#F472B6'),
  ('Moshood Abiola University of Science and Technology, Abeokuta', 'maust.edu.ng', 'MAUST', '#1E1B4B', '#818CF8'),
  ('Zamfara State University', 'zsu.edu.ng', 'ZSU', '#311042', '#E0B0FF'),
  ('Bayelsa Medical University', 'bmu.edu.ng', 'BMU', '#002244', '#FFD700'),
  ('University of Agriculture and Environmental Sciences, Umuagwo, Imo State', 'uaes.edu.ng', 'UAES', '#004B49', '#FFD700'),
  ('Confluence University of Science and Technology, Osara, Kogi', 'custech.edu.ng', 'CUSTECH', '#7A1C1C', '#C0C0C0'),
  ('Bamidele Olumilua University of Science and Technology, Ikere, Ekiti State', 'bouesti.edu.ng', 'BOUESTI', '#1E3A8A', '#3B82F6'),
  ('University of Delta, Agbor', 'ud.edu.ng', 'UD', '#4C1D95', '#F59E0B'),
  ('Delta University of Science and Technology, Ozoro', 'dust.edu.ng', 'DUST', '#065F46', '#10B981'),
  ('Dennis Osadebe University, Asaba', 'dou.edu.ng', 'DOU', '#1E293B', '#94A3B8'),
  ('Lagos State University of Education, Ijanikin', 'lasued.edu.ng', 'LASUED', '#581C87', '#C084FC'),
  ('Lagos State University of Science and Technology, Ikorodu', 'lasustech.edu.ng', 'LASUSTECH', '#881337', '#FB7185'),
  ('Shehu Shagari University of Education, Sokoto', 'ssues.edu.ng', 'SSUES', '#701A75', '#F472B6'),
  ('State University of Medical and Applied Sciences, Igbo-Eno, Enugu', 'sumas.edu.ng', 'SUMAS', '#1E1B4B', '#818CF8'),
  ('University of Ilesa, Osun State', 'ui2.edu.ng', 'UI2', '#311042', '#E0B0FF'),
  ('Emanuel Alayande University of Education, Oyo', 'eaued.edu.ng', 'EAUED', '#002244', '#FFD700'),
  ('Kogi State University, Kabba', 'ksu-kabba.edu.ng', 'KSU-Kabba', '#004B49', '#FFD700'),
  ('AbdulKadir Kure University, Minna, Niger State', 'akku.edu.ng', 'AKKU', '#7A1C1C', '#C0C0C0'),
  ('Kwara State University of Education, Ilorin', 'kwsued.edu.ng', 'KWSUED', '#1E3A8A', '#3B82F6'),
  ('Abdulsalam Abubakar University of Agriculture and Climate Action, Mokwa, Niger State', 'aauaca.edu.ng', 'AAUACA', '#4C1D95', '#F59E0B'),
  ('Ebonyi State University of ICT, Science and Technology, Oferekpe', 'esuict.edu.ng', 'ESUICT', '#065F46', '#10B981'),
  ('Cross River University of Education and Entrepreneurship, Akampa', 'cruee.edu.ng', 'CRUEE', '#1E293B', '#94A3B8'),
  ('Benue State University of Agriculture Science and Technology, Ihugh', 'bsuast.edu.ng', 'BSUAST', '#581C87', '#C084FC'),
  ('University of Aeronautics and Aerospace Engineering, Ezza, Ebonyi State', 'uaae.edu.ng', 'UAAE', '#881337', '#FB7185'),
  ('University of Innovation, Science and Technology, Omuma, Imo State', 'ui3.edu.ng', 'UI3', '#701A75', '#F472B6'),
  ('Babcock University, Ilishan-Remo', 'babcock.edu.ng', 'BABCOCK', '#1E1B4B', '#818CF8'),
  ('Igbinedion University, Okada', 'iu.edu.ng', 'IU', '#311042', '#E0B0FF'),
  ('Madonna University, Okija', 'mu.edu.ng', 'MU', '#002244', '#FFD700'),
  ('Bowen University, Iwo', 'bowen.edu.ng', 'BOWEN', '#004B49', '#FFD700'),
  ('Benson Idahosa University, Benin City', 'biu.edu.ng', 'BIU', '#7A1C1C', '#C0C0C0'),
  ('Covenant University, Ota', 'covenant.edu.ng', 'COVENANT', '#1E3A8A', '#3B82F6'),
  ('Pan-Atlantic University, Lagos', 'pau.edu.ng', 'PAU', '#4C1D95', '#F59E0B'),
  ('American University of Nigeria, Yola', 'aun.edu.ng', 'AUN', '#065F46', '#10B981'),
  ('Ajayi Crowther University, Ibadan', 'acu.edu.ng', 'ACU', '#1E293B', '#94A3B8'),
  ('Al-Hikmah University, Ilorin', 'al-hikmah.edu.ng', 'AL-HIKMAH', '#581C87', '#C084FC'),
  ('Al-Qalam University, Katsina', 'auk.edu.ng', 'AUK', '#881337', '#FB7185'),
  ('Bells University of Technology, Otta', 'bells.edu.ng', 'BELLS', '#701A75', '#F472B6'),
  ('Bingham University, New Karu', 'bingham.edu.ng', 'BINGHAM', '#1E1B4B', '#818CF8'),
  ('Caritas University, Enugu', 'caritas.edu.ng', 'CARITAS', '#311042', '#E0B0FF'),
  ('Crawford University, Igbesa', 'crawford.edu.ng', 'CRAWFORD', '#002244', '#FFD700'),
  ('Crescent University', 'crescent.edu.ng', 'CRESCENT', '#004B49', '#FFD700'),
  ('Kwararafa University, Wukari', 'kuw.edu.ng', 'KUW', '#7A1C1C', '#C0C0C0'),
  ('Lead City University, Ibadan', 'lcu.edu.ng', 'LCU', '#1E3A8A', '#3B82F6'),
  ('Novena University, Ogume', 'novena.edu.ng', 'NOVENA', '#4C1D95', '#F59E0B'),
  ('Renaissance University, Enugu', 'rnu.edu.ng', 'RNU', '#065F46', '#10B981'),
  ('University of Mkar, Mkar', 'unimkar.edu.ng', 'UNIMKAR', '#1E293B', '#94A3B8'),
  ('Joseph Ayo Babalola University, Ikeji-Arakeji', 'jabu.edu.ng', 'JABU', '#581C87', '#C084FC'),
  ('Achievers University, Owo', 'achievers.edu.ng', 'ACHIEVERS', '#881337', '#FB7185'),
  ('Caleb University, Lagos', 'caleb.edu.ng', 'CALEB', '#701A75', '#F472B6'),
  ('Fountain University, Oshogbo', 'fountain.edu.ng', 'FOUNTAIN', '#1E1B4B', '#818CF8'),
  ('African University of Science and Technology, Abuja', 'aust.edu.ng', 'AUST', '#311042', '#E0B0FF'),
  ('Obong University, Obong Ntak', 'obong.edu.ng', 'OBONG', '#002244', '#FFD700'),
  ('Salem University, Lokoja', 'salem.edu.ng', 'SALEM', '#004B49', '#FFD700'),
  ('Tansian University, Umunya', 'tansian.edu.ng', 'TANSIAN', '#7A1C1C', '#C0C0C0'),
  ('Veritas University, Abuja', 'veritas.edu.ng', 'VERITAS', '#1E3A8A', '#3B82F6'),
  ('Wesley University, Ondo', 'wesley.edu.ng', 'WESLEY', '#4C1D95', '#F59E0B'),
  ('Western Delta University, Oghara, Delta State', 'wdu.edu.ng', 'WDU', '#065F46', '#10B981'),
  ('Afe Babalola University, Ado-Ekiti', 'abuad.edu.ng', 'ABUAD', '#1E293B', '#94A3B8'),
  ('Godfrey Okoye University, Ugwuomu-Nike, Enugu State', 'gou.edu.ng', 'GOU', '#581C87', '#C084FC'),
  ('Nile University of Nigeria, Abuja', 'nile.edu.ng', 'NILE', '#881337', '#FB7185'),
  ('Oduduwa University, Ipetumodu, Osun State', 'oduduwa.edu.ng', 'ODUDUWA', '#701A75', '#F472B6'),
  ('Paul University, Awka, Anambra State', 'paul.edu.ng', 'PAUL', '#1E1B4B', '#818CF8'),
  ('Rhema University, Obeama-Asa, Rivers State', 'rhema.edu.ng', 'RHEMA', '#311042', '#E0B0FF'),
  ('Wellspring University, Evbuobanosa, Edo State', 'wellspring.edu.ng', 'WELLSPRING', '#002244', '#FFD700'),
  ('Adeleke University, Ede', 'adeleke.edu.ng', 'ADELEKE', '#004B49', '#FFD700'),
  ('Baze University', 'baze.edu.ng', 'BAZE', '#7A1C1C', '#C0C0C0'),
  ('Landmark University, Omu-Aran', 'landmark.edu.ng', 'LANDMARK', '#1E3A8A', '#3B82F6'),
  ('Glorious Vision University, Ogwa, Edo State', 'gvu.edu.ng', 'GVU', '#4C1D95', '#F59E0B'),
  ('Elizade University, Ilara-Mokin', 'elizade.edu.ng', 'ELIZADE', '#065F46', '#10B981'),
  ('Evangel University, Akaeze', 'evangel.edu.ng', 'EVANGEL', '#1E293B', '#94A3B8'),
  ('Gregory University, Uturu', 'gregory.edu.ng', 'GREGORY', '#581C87', '#C084FC'),
  ('McPherson University, Seriki Sotayo, Ajebo', 'mcu.edu.ng', 'MCU', '#881337', '#FB7185'),
  ('Southwestern University, Oku Owa', 'southwestern.edu.ng', 'SOUTHWESTERN', '#701A75', '#F472B6'),
  ('Augustine University', 'aui.edu.ng', 'AUI', '#1E1B4B', '#818CF8'),
  ('Chrisland University', 'chrisland.edu.ng', 'CHRISLAND', '#311042', '#E0B0FF'),
  ('Edwin Clark University, Kaigbodo', 'ecu.edu.ng', 'ECU', '#002244', '#FFD700'),
  ('Hallmark University, Ijebi Itele, Ogun', 'hallmark.edu.ng', 'HALLMARK', '#004B49', '#FFD700'),
  ('Hezekiah University, Umudi', 'hezekiah.edu.ng', 'HEZEKIAH', '#7A1C1C', '#C0C0C0'),
  ('Kings University, Ode Omu', 'kings.edu.ng', 'KINGS', '#1E3A8A', '#3B82F6'),
  ('Micheal & Cecilia Ibru University', 'mciu.edu.ng', 'MCIU', '#4C1D95', '#F59E0B'),
  ('Mountain Top University', 'mtu.edu.ng', 'MTU', '#065F46', '#10B981'),
  ('Ritman University, Ikot Ekpene, Akwa Ibom', 'ritman.edu.ng', 'RITMAN', '#1E293B', '#94A3B8'),
  ('Summit University, Offa', 'summit.edu.ng', 'SUMMIT', '#581C87', '#C084FC'),
  ('Christopher University, Mowe', 'christopher.edu.ng', 'CHRISTOPHER', '#881337', '#FB7185'),
  ('Kola Daisi University, Ibadan', 'kdu.edu.ng', 'KDU', '#701A75', '#F472B6'),
  ('Anchor University, Ayobo, Lagos State', 'anchor.edu.ng', 'ANCHOR', '#1E1B4B', '#818CF8'),
  ('Dominican University, Ibadan', 'dominican.edu.ng', 'DOMINICAN', '#311042', '#E0B0FF'),
  ('Legacy University, Okija, Anambra State', 'legacy.edu.ng', 'LEGACY', '#002244', '#FFD700'),
  ('Arthur Jarvis University, Akpoyubo, Cross River State', 'aju.edu.ng', 'AJU', '#004B49', '#FFD700'),
  ('Ojaja University, Eiyenkorin, Kwara State', 'ojaja.edu.ng', 'OJAJA', '#7A1C1C', '#C0C0C0'),
  ('Coal City University, Enugu State', 'ccu.edu.ng', 'CCU', '#1E3A8A', '#3B82F6'),
  ('Clifford University, Owerrinta, Abia State', 'clifford.edu.ng', 'CLIFFORD', '#4C1D95', '#F59E0B'),
  ('Spiritan University, Nneochi, Abia State', 'spiritan.edu.ng', 'SPIRITAN', '#065F46', '#10B981'),
  ('Precious Cornerstone University, Oyo', 'pcu.edu.ng', 'PCU', '#1E293B', '#94A3B8'),
  ('PAMO University of Medical Sciences, Port Harcourt', 'pamo.edu.ng', 'PAMO', '#581C87', '#C084FC'),
  ('Atiba University, Oyo', 'atiba.edu.ng', 'ATIBA', '#881337', '#FB7185'),
  ('Eko University of Medical and Health Sciences, Ijanikin, Lagos', 'ekounimed.edu.ng', 'EKOUNIMED', '#701A75', '#F472B6'),
  ('Skyline University, Kano', 'sun.edu.ng', 'SUN', '#1E1B4B', '#818CF8'),
  ('Greenfield University, Kaduna', 'gfu.edu.ng', 'GFU', '#311042', '#E0B0FF'),
  ('Dominion University, Ibadan', 'dominion.edu.ng', 'DOMINION', '#002244', '#FFD700'),
  ('Trinity University, Ogun State', 'trinity.edu.ng', 'TRINITY', '#004B49', '#FFD700'),
  ('Westland University, Iwo, Osun State', 'westland.edu.ng', 'WESTLAND', '#7A1C1C', '#C0C0C0'),
  ('Topfaith University, Mkpatak, Akwa Ibom State', 'topfaith.edu.ng', 'TOPFAITH', '#1E3A8A', '#3B82F6'),
  ('Thomas Adewumi University, Oko-Irese, Kwara State', 'tau.edu.ng', 'TAU', '#4C1D95', '#F59E0B'),
  ('Maranatha University, Lagos', 'maranatha.edu.ng', 'MARANATHA', '#065F46', '#10B981'),
  ('Ave Maria University, Piyanko, Nasarawa State', 'avu.edu.ng', 'AVU', '#1E293B', '#94A3B8'),
  ('Al-Istiqama University, Sumaila, Kano State', 'al-istiqama.edu.ng', 'AL-ISTIQAMA', '#581C87', '#C084FC'),
  ('Mudiame University, Irrua, Edo State', 'mudiame.edu.ng', 'MUDIAME', '#881337', '#FB7185'),
  ('Havilla University, Nde-Ikom, Cross River State', 'havilla.edu.ng', 'HAVILLA', '#701A75', '#F472B6'),
  ('Claretian University of Nigeria, Nekede, Imo State', 'cun.edu.ng', 'CUN', '#1E1B4B', '#818CF8'),
  ('Karl-Kumm University, Vom, Plateau State', 'kku.edu.ng', 'KKU', '#311042', '#E0B0FF'),
  ('James Hope University, Lagos', 'jhu.edu.ng', 'JHU', '#002244', '#FFD700'),
  ('Maryam Abacha American University of Nigeria, Kano State', 'maaun.edu.ng', 'MAAUN', '#004B49', '#FFD700'),
  ('Capital City University, Kano State', 'ccuk.edu.ng', 'CCUK', '#7A1C1C', '#C0C0C0'),
  ('Ahman Pategi University, Kwara State', 'apu.edu.ng', 'APU', '#1E3A8A', '#3B82F6'),
  ('University of Offa, Kwara State', 'unioffa.edu.ng', 'UNIOFFA', '#4C1D95', '#F59E0B'),
  ('Mewar International University, Masaka, Nasarawa State', 'mewar.edu.ng', 'MEWAR', '#065F46', '#10B981'),
  ('Edusoko University, Bida, Niger State', 'edusoko.edu.ng', 'EDUSOKO', '#1E293B', '#94A3B8'),
  ('Philomath University, Kuje, Abuja', 'philomath.edu.ng', 'PHILOMATH', '#581C87', '#C084FC'),
  ('Khadija University, Majia, Jigawa State', 'khadija.edu.ng', 'KHADIJA', '#881337', '#FB7185'),
  ('Anan University, Kwall, Plateau State', 'anan.edu.ng', 'ANAN', '#701A75', '#F472B6'),
  ('North Eastern University, Gombe', 'neu.edu.ng', 'NEU', '#1E1B4B', '#818CF8'),
  ('Al-Ansar University, Maiduguri, Borno', 'al-ansar.edu.ng', 'AL-ANSAR', '#311042', '#E0B0FF'),
  ('Margaret Lawrence University, Umunede, Delta State', 'mlu.edu.ng', 'MLU', '#002244', '#FFD700'),
  ('Khalifa Isiyaku Rabiu University, Kano', 'khairu.edu.ng', 'KHAIRU', '#004B49', '#FFD700'),
  ('Sports University, Idumuje-Ugboko, Delta State', 'sportsuni.edu.ng', 'SPORTSUNI', '#7A1C1C', '#C0C0C0'),
  ('Baba Ahmed University, Kano State', 'bau.edu.ng', 'BAU', '#1E3A8A', '#3B82F6'),
  ('Saisa University of Medical Sciences and Technology, Sokoto State', 'saisa.edu.ng', 'SAISA', '#4C1D95', '#F59E0B'),
  ('Nigerian British University, Asa, Abia State', 'nbu.edu.ng', 'NBU', '#065F46', '#10B981'),
  ('Peter University, Achina-Onneh, Anambra State', 'peter.edu.ng', 'PETER', '#1E293B', '#94A3B8'),
  ('Newgate University, Minna, Niger State', 'newgate.edu.ng', 'NEWGATE', '#581C87', '#C084FC'),
  ('European University of Nigeria, Duboyi, FCT', 'eun.edu.ng', 'EUN', '#881337', '#FB7185'),
  ('NorthWest University, Sokoto State', 'nwus.edu.ng', 'NWUS', '#701A75', '#F472B6'),
  ('Rayhaan University, Kebbi', 'rayhaan.edu.ng', 'RAYHAAN', '#1E1B4B', '#818CF8'),
  ('Muhammad Kamalud University, Kwara', 'mku.edu.ng', 'MKU', '#311042', '#E0B0FF'),
  ('Sam Maris University, Ondo', 'smu.edu.ng', 'SMU', '#002244', '#FFD700'),
  ('Aletheia University, Ago-Iwoye, Ogun State', 'aletheia.edu.ng', 'ALETHEIA', '#004B49', '#FFD700'),
  ('Lux Mundi University, Umuahia, Abia State', 'luxmundi.edu.ng', 'LUXMUNDI', '#7A1C1C', '#C0C0C0'),
  ('Maduka University, Ekwegbe, Enugu State', 'maduka.edu.ng', 'MADUKA', '#1E3A8A', '#3B82F6'),
  ('PeaceLand University, Enugu State', 'peaceland.edu.ng', 'PEACELAND', '#4C1D95', '#F59E0B'),
  ('Amadeus University, Amizi, Abia State', 'amadeus.edu.ng', 'AMADEUS', '#065F46', '#10B981'),
  ('Vision University, Ikogbo, Ogun State', 'vision.edu.ng', 'VISION', '#1E293B', '#94A3B8'),
  ('Azman University, Kano State', 'azman.edu.ng', 'AZMAN', '#581C87', '#C084FC'),
  ('Huda University, Gusau, Zamfara State', 'huda.edu.ng', 'HUDA', '#881337', '#FB7185'),
  ('Franco British International University, Kaduna State', 'fbiu.edu.ng', 'FBIU', '#701A75', '#F472B6'),
  ('Canadian University of Nigeria, Abuja', 'cun-abuja.edu.ng', 'CUN-Abuja', '#1E1B4B', '#818CF8'),
  ('Gerar University of Medical Science, Imope Ijebu, Ogun State', 'gums.edu.ng', 'GUMS', '#311042', '#E0B0FF'),
  ('British Canadian University, Obufu, Cross River State', 'bcu.edu.ng', 'BCU', '#002244', '#FFD700'),
  ('Hensard University, Toru-Orua, Sagbama, Bayelsa State', 'hensard.edu.ng', 'HENSARD', '#004B49', '#FFD700'),
  ('Amaj University, Kwali, Abuja', 'amaj.edu.ng', 'AMAJ', '#7A1C1C', '#C0C0C0'),
  ('Phoenix University, Agwada, Nasarawa State', 'phoenix.edu.ng', 'PHOENIX', '#1E3A8A', '#3B82F6'),
  ('Wigwe University, Isiokpo, Rivers State', 'wigwe.edu.ng', 'WIGWE', '#4C1D95', '#F59E0B'),
  ('Hillside University of Science and Technology, Okemisi, Ekiti State', 'hust.edu.ng', 'HUST', '#065F46', '#10B981'),
  ('University on the Niger, Umunya, Anambra State', 'uniniger.edu.ng', 'UNINIGER', '#1E293B', '#94A3B8'),
  ('Elrazi Medical University, Yargaya, Kano State', 'emu.edu.ng', 'EMU', '#581C87', '#C084FC'),
  ('Venite University, Iloro-Ekiti, Ekiti State', 'venite.edu.ng', 'VENITE', '#881337', '#FB7185'),
  ('Shanahan University, Onitsha, Anambra State', 'shanahan.edu.ng', 'SHANAHAN', '#701A75', '#F472B6'),
  ('The Duke Medical University, Calabar, Cross River State', 'tdmu.edu.ng', 'TDMU', '#1E1B4B', '#818CF8'),
  ('Mercy Medical University, Iwo, Ogun State', 'mmu.edu.ng', 'MMU', '#311042', '#E0B0FF'),
  ('Cosmopolitan University, Abuja', 'cosmopolitan.edu.ng', 'COSMOPOLITAN', '#002244', '#FFD700'),
  ('Miva Open University, Abuja', 'miva.edu.ng', 'MIVA', '#004B49', '#FFD700'),
  ('Iconic Open University, Sokoto State', 'iconic.edu.ng', 'ICONIC', '#7A1C1C', '#C0C0C0'),
  ('West Midlands Open University, Ibadan, Oyo State', 'wmou.edu.ng', 'WMOU', '#1E3A8A', '#3B82F6'),
  ('Al-Muhibbah Open University, Abuja', 'al-muhibbah.edu.ng', 'AL-MUHIBBAH', '#4C1D95', '#F59E0B'),
  ('El-Amin University, Minna, Niger State', 'el-amin.edu.ng', 'EL-AMIN', '#065F46', '#10B981'),
  ('College of Petroleum and Energy Studies, Kaduna State', 'cpes.edu.ng', 'CPES', '#1E293B', '#94A3B8'),
  ('Jewel University, Gombe State', 'jewel.edu.ng', 'JEWEL', '#581C87', '#C084FC'),
  ('Prime University, Kuje, Abuja', 'prime.edu.ng', 'PRIME', '#881337', '#FB7185'),
  ('Nigerian University of Technology and Management, Apapa, Lagos State', 'nutm.edu.ng', 'NUTM', '#701A75', '#F472B6'),
  ('Al-Bayan University, Ankpa, Kogi State', 'al-bayan.edu.ng', 'AL-BAYAN', '#1E1B4B', '#818CF8'),
  ('Lighthouse University, Evbobanosa, Edo State', 'lighthouse.edu.ng', 'LIGHTHOUSE', '#311042', '#E0B0FF'),
  ('African University of Economics, Abuja', 'aue.edu.ng', 'AUE', '#002244', '#FFD700'),
  ('New City University, Ayetoro, Ogun State', 'newcity.edu.ng', 'NEWCITY', '#004B49', '#FFD700'),
  ('University of Fortune, Igbotako, Ondo State', 'fortune.edu.ng', 'FORTUNE', '#7A1C1C', '#C0C0C0'),
  ('Eranova University, Abuja', 'eranova.edu.ng', 'ERANOVA', '#1E3A8A', '#3B82F6'),
  ('Minaret University, Ikirun, Osun State', 'minaret.edu.ng', 'MINARET', '#4C1D95', '#F59E0B'),
  ('Abdulrasaq Abubakar Toyin University, Ganmo, Ilorin, Kwara State', 'aatu.edu.ng', 'AATU', '#065F46', '#10B981'),
  ('Southern Atlantic University, Uyo, Akwa Ibom State', 'sau.edu.ng', 'SAU', '#1E293B', '#94A3B8'),
  ('Lens University, Ilemona, Kwara State', 'lens.edu.ng', 'LENS', '#581C87', '#C084FC'),
  ('Monarch University, Iyesi-Ota, Ogun State', 'monarch.edu.ng', 'MONARCH', '#881337', '#FB7185'),
  ('Tonine Iredia University of Communication, Benin City, Edo State', 'tiuc.edu.ng', 'TIUC', '#701A75', '#F472B6'),
  ('Isaac Balami University of Aeronautics and Management, Lagos State', 'ibuam.edu.ng', 'IBUAM', '#1E1B4B', '#818CF8'),
  ('Kevin Eze University, Mgbowo, Enugu State', 'keu.edu.ng', 'KEU', '#311042', '#E0B0FF'),
  ('Tazkiyah University, Kaduna State', 'tazkiyah.edu.ng', 'TAZKIYAH', '#002244', '#FFD700'),
  ('Leadership University, Abuja', 'leadership.edu.ng', 'LEADERSHIP', '#004B49', '#FFD700'),
  ('Jimoh Babalola University, Ilorin, Kwara State', 'jbu.edu.ng', 'JBU', '#7A1C1C', '#C0C0C0'),
  ('Bridget University Mbaise, Okirika-Nweke, Imo State', 'bridget.edu.ng', 'BRIDGET', '#1E3A8A', '#3B82F6'),
  ('Greenland University, Jalingo, Taraba State', 'greenland.edu.ng', 'GREENLAND', '#4C1D95', '#F59E0B'),
  ('JEFAP University, Suleja, Niger State', 'jefap.edu.ng', 'JEFAP', '#065F46', '#10B981'),
  ('Azione Verde University, Amaigbo, Imo State', 'avu-azione.edu.ng', 'AVU-Azione', '#1E293B', '#94A3B8'),
  ('Unique Open University, Ojo, Lagos State', 'uou.edu.ng', 'UOU', '#581C87', '#C084FC'),
  ('American Open University, Abeokuta, Ogun State', 'aou.edu.ng', 'AOU', '#881337', '#FB7185')
ON CONFLICT (domain) DO UPDATE SET
  name = EXCLUDED.name,
  short_name = EXCLUDED.short_name,
  primary_color = EXCLUDED.primary_color,
  secondary_color = EXCLUDED.secondary_color;


-- ─── 2. ADD MISSING COLUMNS TO PROFILES ───
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS university_id UUID REFERENCES public.universities(id);
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS gender TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS id_card_url TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS id_card_status TEXT DEFAULT 'not_uploaded';
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS invite_code TEXT UNIQUE;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS invited_by TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS forced_signout_at TIMESTAMPTZ;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS joined_global_hub BOOLEAN DEFAULT false;


-- ─── 3. ADD MISSING COLUMNS TO POSTS & VIEWS ───
ALTER TABLE public.posts ADD COLUMN IF NOT EXISTS posted_to_global_hub BOOLEAN DEFAULT false;

CREATE OR REPLACE VIEW public.local_posts AS
SELECT * FROM public.posts
WHERE posted_to_global_hub = false;

CREATE OR REPLACE VIEW public.global_posts AS
SELECT * FROM public.posts
WHERE posted_to_global_hub = true;


-- ─── 4. CREATE CASCADE DELETE TRIGGER FOR PROFILES ───
CREATE OR REPLACE FUNCTION public.handle_auth_user_deleted()
RETURNS TRIGGER AS $$
BEGIN
  DELETE FROM public.profiles WHERE id = OLD.id;
  RETURN OLD;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_handle_auth_user_deleted ON auth.users;
CREATE TRIGGER trg_handle_auth_user_deleted
  AFTER DELETE ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_auth_user_deleted();
